### ISSUE TITLE
Support media

### ISSUE THREAD

**Issue by weberc2** [SlyMarbo/rss#13]
Hi, I was wondering about supporting media content like <enclosure /> --are there any plans to add such support?

**Comment by SlyMarbo** [comment]
Could you give a little more detail? What sort of support would you be looking for?

**Comment by weberc2** [comment]
Podcasts, for example. So for RSS, this would be the <enclosure /> tag, and I think Atom uses <media:content> or some such.

**Comment by SlyMarbo** [comment]
I'd certainly be happy to look into it, although I'm really busy at the moment. Could you find an example URL so I know what sort of structure to look for?

**Comment by weberc2** [comment]
http://en.wikipedia.org/wiki/RSS_enclosure has this example: `<enclosure url="http://example.com/file.mp3" length="123456789" type="audio/mpeg" />`

**Comment by SlyMarbo** [comment]
I've tested the new code against a few small examples but let me know if it fails with real data.
