### ISSUE TITLE
Enclosures attributes not parsed

### ISSUE THREAD

**Issue by adamveld12** [SlyMarbo/rss#18]
http://cyber.law.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt

According to the spec the enclosure tag has 3 attributes. The Rss2_0Enclosure is setup to parse those attributes as sub elements.

**Comment by SlyMarbo** [comment]
`TestEnclosure` is still passing and the input and output look like they conform with the standard. Could you give an example that demonstrates incorrect behaviour?

**Comment by adamveld12** [comment]
Here is one example feed I was using: http://www.neozaz.com/feed/swic

I managed to fix it on my end by adding ',attr' on the end of the annotations like this in rss 2.0.go

```
type rss2_0Enclosure struct {
	XMLName xml.Name `xml:"enclosure"`
	Url     string   `xml:"url,attr"`
	Type    string   `xml:"type,attr"`
	Length  int      `xml:"length,attr"`
}
```

I'm also using go 1.5.1

**Comment by adamveld12** [comment]
I also cannot run the tests, I get this

```
$ go test
--- FAIL: TestDatabaseReenabled (0.00s)
        database_test.go:40: Should record a new entry.
FAIL
exit status 1
FAIL    github.com/slymarbo/rss 0.023s
```

Maybe it's just because of the new version of go?

**Comment by SlyMarbo** [comment]
Yeah, I spotted that too. I've pushed a fix

**Comment by adamveld12** [comment]
Awesome, thanks!

**Comment by milosgajdos83** [comment]
Should this issue be closed then ? It kinda confused me :-)

**Comment by adamveld12** [comment]
Yeah, everything is working for me.
