### ISSUE TITLE
parsing time error

### ISSUE THREAD

**Issue by monoflash** [SlyMarbo/rss#28]
I'm trying to get the rss ("http://mtgjson.com/atom.xml") and get the following error:
parsing time "2016-02-28T00:00:00" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "Z07:00"

**Comment by SlyMarbo** [comment]
This looks like a slightly unusual time format. You can add it to the known formats with the following:

```go
rss.TimeLayouts = append(rss.TimeLayouts, "2006-01-02T15:04:05")
```

**Comment by monoflash** [comment]
I did not notice the ability to add time formats.
Its work!
Thanks.
