### ISSUE TITLE
"expected element type <feed> but have <html>"

### ISSUE THREAD

**Issue by shackra** [SlyMarbo/rss#29]
Two feeds makes this package output this error. I'm attaching the offending feeds.

[laprensalibre.txt](https://github.com/SlyMarbo/rss/files/237782/laprensalibre.txt)
[crhoy.txt](https://github.com/SlyMarbo/rss/files/237783/crhoy.txt)

Is there a workaround for this issue?

**Comment by SlyMarbo** [comment]
At a quick glance, the first file is a web page, not an RSS feed, so the error is correct. The second file looks roughly sane, but it does have some unexpected trailing text. I'll see if I can track down what's going wrong, but it may take a while.

**Comment by shackra** [comment]
Thank you very much!

El miércoles 27 de abril del 2016 a las 1147 horas, Jamie Hall escribió:

> At a quick glance, the first file is a web page, not an RSS feed, so the error is correct. The second file looks roughly sane, but it does have some unexpected trailing text. I'll see if I can track down what's going wrong, but it may take a while.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SlyMarbo/rss/issues/29#issuecomment-215168712


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by tjgillies** [comment]
Getting the same for http://readwrite.com/feed I'll fork the repo and try to submit a PR, I'm learning go

**Comment by tjgillies** [comment]
I needed to set user agent. Turns it was 403. Works fine now.

**Comment by Fossil01** [comment]
@tjgillies How did you set the user-agent?

**Comment by SlyMarbo** [comment]
@Fossil01 See #41

**Comment by demas** [comment]
I have the same issue on every Reddit feed (https://www.reddit.com/r/golang/.rss)
