### ISSUE TITLE
cannot parse "Sat, 30 Abr 2016 08:28:59 GMT" as "2006"

### ISSUE THREAD

**Issue by shackra** [SlyMarbo/rss#30]
As far as I can see, the package tries to parse time with the default string format provided by the `time` package...

Providing a way to set the string format for parsing certain feeds which don't use a orthodox (from `time` point of view) display format for time would be helpful.

**Comment by SlyMarbo** [comment]
This is already possible by modifying `rss.TimeLayouts`. See `time.go` for more details.

**Comment by shackra** [comment]
Oh! my bad :)

El sábado 30 de abril del 2016 a las 0704 horas, Jamie Hall escribió:

> This is already possible by modifying `rss.TimeLayouts`. See `time.go` for more details.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SlyMarbo/rss/issues/30#issuecomment-215962088


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra
