### ISSUE TITLE
Support for non standard date format

### ISSUE THREAD

**Issue by zaddok** [SlyMarbo/rss#34]
While reading:

    http://rss.wn.com/English/top-stories

The following error is returned:

    parsing time "Mon, 29 Aug 2016 02:52 GMT" as
    "2006-01-02T15:04:05.999999999Z07:00": cannot parse
    "Mon, 29 Aug 2016 02:52 GMT" as "2006"

__PS:__ I know providers should use the standard date format, but sometimes this is out of our control.

**Comment by SlyMarbo** [comment]
See #30
