### ISSUE TITLE
Maximum number of posts in feed struct?

### ISSUE THREAD

**Issue by Fossil01** [SlyMarbo/rss#43]
Right now I'm testing with an RSS feed which returns 100 posts. If the feed updates and the update() function is called then new posts are appended to the Feed struct resulting in a huge struct over time. How can I make sure it never contains more than 100 posts?

**Comment by SlyMarbo** [comment]
If it gets big enough to matter, you can make a new slice and copy in the ~100 most recent items. If the server only sends the 100 most recent items, you shouldn't get any duplication.
