### ISSUE TITLE
What happened to rss.CacheParsedItemIDs

### ISSUE THREAD

**Issue by zaddok** [SlyMarbo/rss#49]
My code no longer works. I assume this was changed recently. How do we reproduce this behaviour in the new versions?

See: https://gowalker.org/github.com/SlyMarbo/rss#CacheParsedItemIDs

I only remember I had to use this function to work around a bug I was encountering. I can't remember why exactly I was using it, it was a while ago now. It was likely to do with either running out of memory in a long running process, or to seeing updates to feeds coming through.

**Comment by SlyMarbo** [comment]
Hi,

The function is no longer necessary; caching is now automatic, so your code should continue to work the same way.

**Comment by zaddok** [comment]
So this library no longer supports turning caching off?  I really don't want tens of thousands of records collecting in memory over the course of the week... we probably have to start restarting the app every few days or create our own branch of this library.

**Comment by SlyMarbo** [comment]
If you don't want caching, simply use `Fetch` every time, rather than using `Update` after the first `Fetch`, but it's worth noting that the nature of RSS means that you'll probably get a lot of duplicate data.
