### ISSUE TITLE
`length = ""` leads to `strconv.ParseInt: parsing "": invalid syntax`

### ISSUE THREAD

**Issue by haarts** [SlyMarbo/rss#53]
I'm trying to parse this feed: http://www.juliabloggers.com/feed/. Which is invalid. It defines some length to be an empty string, suckers. See here: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.juliabloggers.com%2Ffeed%2F#l147

Perhaps there's some graceful way of this lib to deal with such a case?

**Comment by lutzhorn** [comment]
What happens right now when you try to parse this feed? What error do you get? What result do you expect?

**Comment by SlyMarbo** [comment]
Unfortunately the `strconv` error takes place in the `xml` package, so to make the error more clear I would have to do a lot of introspection on the error returned there, which seems rather fragile.
