### ISSUE TITLE
Supoort HTTP Conditional GET

### ISSUE THREAD

**Issue by lutzhorn** [SlyMarbo/rss#54]
What do you think about supporting [HTTP Conditional GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests)? As far as I understand the current code, the HTTP GET requests made don't use the `If-None-Match` or `If-Modified-Since` HTTP headers. This results in the full feed XML always being downloaded.

Since many servers support HTTP Conditional GET, it would be a way to reduce network load to not only pass the URL but also values for these headers. `rss.Fetch` would have to return the values of the `ETag` and `Last-Modified` headers, if present on the response. The code calling `rss.Fetch` could then remember the values of these headers and pass them in later requests.

What do you think?

**Comment by SlyMarbo** [comment]
It is possible for users of the package to do this themselves by using their own `http.Client` with `rss.FetchByClient`. It would be an improvement for `rss.Fetch` to add this behaviour, but I don't have the time to add it myself.

**Comment by lutzhorn** [comment]
OK, I'll take a look how much work this would be and try to implement this in a fork.
