### ISSUE TITLE
support for yahoo media rss extensions (e.g. YouTube feeds)

### ISSUE THREAD

**Issue by mmasouras** [SlyMarbo/rss#62]
I can't fully parse YouTube RSS feeds (atom) - e.g. 
https://www.youtube.com/feeds/videos.xml?channel_id=UCUJeW9pnxhDZ5GA0TNRl4zg

I get title, link, timestamp and guid, but importantly not the summary, or any images. Here's how an Item looks:

2017/11/14 15:45:42 Item "Updated 2018 Yamaha MT-07 First Look"
	"https://www.youtube.com/watch?v=J1uq9oBm7B8"
	23:44:37 +0000 14/11/2017
	"yt:video:J1uq9oBm7B8"
	Read: false
	""

**Comment by SlyMarbo** [comment]
Looking briefly at the data, it appears that the data does not conform to the standard.
