### ISSUE TITLE
Is a RSS channel with no feeds faulty?

### ISSUE THREAD

**Issue by lutzhorn** [SlyMarbo/rss#64]
Consider [a RSS feed with no feeds](https://www.bitkom.org/bitkom/org/Presse/Blog/index.xml):

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>Willkommen auf unserem Blog</title>
    <link>https://www.bitkom.org//bitkom/org/Presse/Blog/index.jsp</link>
    <description>Der RSS Feed mit den aktuellsten Blogbeiträgen</description>
    <language>de</language>
  </channel>
</rss>
```

For such a feed `parseRSS2` returns an error:

https://github.com/SlyMarbo/rss/blob/6288663a2d2f9d8c80085f6d2ae9b80cf35e355a/rss_2.0.go#L65

But such a feed [is valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.bitkom.org%2Fbitkom%2Forg%2FPresse%2FBlog%2Findex.xml).

Wouldn't it more consistent to not return an error but a `Feed` with no items?

**Comment by SlyMarbo** [comment]
Very sensible suggestion, which I've implemented. Thanks!

**Comment by lutzhorn** [comment]
Great, thank you!
