### ISSUE TITLE
Support HTTP Basic Authentication

### ISSUE THREAD

**Issue by lutzhorn** [SlyMarbo/rss#68]
I suggest to add support for HTTP Basic Authentication. This would allow access to password protected feeds. `net/http.Request` provides [`SetBasicAuth`](https://golang.org/pkg/net/http/#Request.SetBasicAuth) which could be used.

Do you have plans and/or time to implement this? If not, I'd try to add this and then submit a PR.

**Comment by SlyMarbo** [comment]
I'm afraid I don't have plans/time to implement this, but it could probably just be an example using `rss.FetchFunc` where you create the request using `http.NewRequest("GET", url, nil)`, modify the request with `SetBasicAuth`, then use `http.DefaultClient.Do(req)` in the `FetchFunc`.

**Comment by lutzhorn** [comment]
Putting the credentials into the URL like `https://user:secret@example.com/feed.rss` works for the site I want to acces. So this already works.
