### ISSUE TITLE
Attempting to fetch certain feed blocks indefinitely

### ISSUE THREAD

**Issue by biox** [SlyMarbo/rss#84]
hi! i recently attempted to fetch a certain feed, and slymarbo/rss blocks indefinitely - here's a reproducible example:

```
package main

import (
	"github.com/SlyMarbo/rss"
	"log"
)

func main() {
	feed, err := rss.Fetch("https://www.idealista.pt/news/rss/v2/latest-news.xml")
	if err != nil {
		log.Println(err)
	}

	err = feed.Update()
	if err != nil {
		log.Println(err)
	}
}
```

i've attached the XML of that feed as it exists today, in case the example i've provided stops reproducing: 
[bad-xml.txt](https://github.com/SlyMarbo/rss/files/15052309/bad-xml.txt)

**Comment by SlyMarbo** [comment]
Thanks for reporting this. Sorry for the silly bug. It should be fixed now.
